unsigned long _ABVAR_1_migikyori = 0UL ;
int ardublockUltrasonicSensorCodeAutoGeneratedReturnCM(int trigPin, int echoPin)
{
  long duration;
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(20);
  digitalWrite(trigPin, LOW);
  duration = pulseIn(echoPin, HIGH);
  duration = duration / 59;
  if ((duration < 2) || (duration > 300)) return false;
  return duration;
}

unsigned long _ABVAR_2_maekyori = 0UL ;

void setup()
{
  digitalWrite( 13 , LOW );

  digitalWrite( 11 , LOW );

  pinMode( 8 , OUTPUT);
  pinMode( 3 , OUTPUT);
  pinMode( 9 , OUTPUT);
  pinMode( 5 , OUTPUT);
  pinMode( 4 , OUTPUT);
  pinMode( 6 , OUTPUT);
}

void loop()
{
  _ABVAR_1_migikyori = 	ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 13 , 12 ) ;
  delayMicroseconds( 5000 );
  _ABVAR_2_maekyori = 	ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 11 , 7 ) ;
}

void mae()
{
  digitalWrite(8 , HIGH);
  digitalWrite(3 , LOW);
  analogWrite(9 , 50);
  digitalWrite(5 , HIGH);
  digitalWrite(4 , LOW);
  analogWrite(6 , 50);
}

void ushiro()
{
  digitalWrite(8 , LOW);
  digitalWrite(3 , HIGH);
  analogWrite(9 , 50);
  digitalWrite(5 , LOW);
  digitalWrite(4 , HIGH);
  analogWrite(6 , 50);
}

void stop()
{
  digitalWrite(8 , LOW);
  digitalWrite(3 , LOW);
  digitalWrite(5 , LOW);
  digitalWrite(4 , LOW);
}

void hidari()
{
  digitalWrite(8 , LOW);
  digitalWrite(3 , HIGH);
  analogWrite(9 , 50);
  digitalWrite(5 , HIGH);
  digitalWrite(4 , LOW);
  analogWrite(6 , 50);
}

void migi()
{
  digitalWrite(8 , HIGH);
  digitalWrite(3 , LOW);
  analogWrite(9 , 50);
  digitalWrite(5 , LOW);
  digitalWrite(4 , HIGH);
  analogWrite(6 , 50);
}


